[build]
target = "x86_64-unknown-uefi"
# LLVM ERROR回避のため、明示的なznver2指定。
# 特定の機能がcompiler_builtinsを壊す場合は、ここで-target-featureを調整する。
rustflags = [
    "-C", "target-cpu=znver2",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
